import React from "react";
import {
  Page,
  Text,
  View,
  Document,
  StyleSheet,
  Link,
} from "@react-pdf/renderer";
import { Book, Page as BookPage } from "../../types";

// Styles for bilingual side-by-side layout
const styles = StyleSheet.create({
  page: {
    flexDirection: "column",
    backgroundColor: "#ffffff",
    paddingTop: 60,
    paddingBottom: 40,
    paddingHorizontal: 30,
    fontFamily: "Times-Roman",
    fontSize: 9,
    lineHeight: 1.4,
  },
  titlePage: {
    flexDirection: "column",
    backgroundColor: "#ffffff",
    padding: 60,
    fontFamily: "Times-Roman",
    justifyContent: "center",
    alignItems: "center",
  },
  title: {
    fontSize: 28,
    fontWeight: "bold",
    textAlign: "center",
    marginBottom: 15,
  },
  subtitle: {
    fontSize: 16,
    textAlign: "center",
    color: "#666666",
    marginBottom: 8,
  },
  author: {
    fontSize: 18,
    textAlign: "center",
    marginBottom: 30,
  },
  metadata: {
    fontSize: 11,
    color: "#666666",
    textAlign: "center",
    marginTop: 40,
  },
  metadataLine: {
    marginBottom: 6,
    textAlign: "center",
  },
  // Page header
  pageHeader: {
    position: "absolute",
    top: 20,
    left: 30,
    right: 30,
    flexDirection: "row",
    justifyContent: "space-between",
    fontSize: 9,
    color: "#666666",
    paddingBottom: 8,
    borderBottomWidth: 0.5,
    borderBottomColor: "#cccccc",
  },
  // Two-column layout
  columnsContainer: {
    flexDirection: "row",
    flex: 1,
  },
  column: {
    flex: 1,
    paddingHorizontal: 10,
  },
  leftColumn: {
    borderRightWidth: 0.5,
    borderRightColor: "#dddddd",
  },
  columnHeader: {
    fontSize: 10,
    fontWeight: "bold",
    marginBottom: 8,
    paddingBottom: 4,
    borderBottomWidth: 0.5,
    borderBottomColor: "#cccccc",
    color: "#333333",
  },
  pageMarker: {
    fontSize: 10,
    fontWeight: "bold",
    marginTop: 15,
    marginBottom: 8,
    color: "#666666",
    backgroundColor: "#f5f5f5",
    padding: 4,
  },
  textContent: {
    fontSize: 9,
    lineHeight: 1.5,
    textAlign: "justify",
  },
  noContent: {
    fontSize: 9,
    color: "#999999",
    fontStyle: "italic",
  },
  // Footer
  pageFooter: {
    position: "absolute",
    bottom: 20,
    left: 30,
    right: 30,
    flexDirection: "row",
    justifyContent: "space-between",
    fontSize: 8,
    color: "#999999",
  },
});

interface BilingualPdfProps {
  bookDetails: Book;
  pages: BookPage[];
}

const BilingualPdfDocument: React.FC<BilingualPdfProps> = ({ bookDetails, pages }) => {
  // Sort pages by page number
  const sortedPages = [...pages].sort((a, b) => a.page_number - b.page_number);

  // Filter to only pages with content
  const pagesWithContent = sortedPages.filter(
    (page) => page.ocr?.data?.trim() || page.translation?.data?.trim()
  );

  const sourceLanguage = bookDetails.language || "Original";
  const targetLanguage = pagesWithContent[0]?.translation?.language || "English";

  return (
    <Document
      title={`${bookDetails.title} - Bilingual Edition`}
      author={bookDetails.author}
      creator="Source Library - sourcelibrary.vercel.app"
    >
      {/* Title Page */}
      <Page size="A4" style={styles.titlePage}>
        <Text style={styles.title}>{bookDetails.display_title || bookDetails.title}</Text>
        {bookDetails.display_title && (
          <Text style={styles.subtitle}>{bookDetails.title}</Text>
        )}
        <Text style={styles.author}>by {bookDetails.author}</Text>

        <View style={styles.metadata}>
          <Text style={styles.metadataLine}>Bilingual Edition</Text>
          <Text style={styles.metadataLine}>
            {sourceLanguage} → {targetLanguage}
          </Text>
          {bookDetails.published && (
            <Text style={styles.metadataLine}>Originally published: {bookDetails.published}</Text>
          )}
          <Text style={styles.metadataLine}>{pagesWithContent.length} pages</Text>
          <Text style={{ ...styles.metadataLine, marginTop: 30 }}>
            Generated by Source Library
          </Text>
          <Link src="https://sourcelibrary.vercel.app" style={{ fontSize: 10, color: "#666666" }}>
            sourcelibrary.vercel.app
          </Link>
        </View>
      </Page>

      {/* Content Pages - Bilingual Layout */}
      <Page size="A4" orientation="landscape" style={styles.page} wrap>
        {/* Fixed Header */}
        <View style={styles.pageHeader} fixed>
          <Text>{bookDetails.display_title || bookDetails.title}</Text>
          <Text render={({ pageNumber, totalPages }) => `${pageNumber} / ${totalPages}`} />
        </View>

        {/* Two Column Content */}
        <View style={styles.columnsContainer}>
          {/* Left Column - Original/OCR */}
          <View style={[styles.column, styles.leftColumn]}>
            <Text style={styles.columnHeader}>{sourceLanguage} (Original)</Text>
            {pagesWithContent.map((page) => (
              <View key={`ocr-${page.id}`} wrap={false}>
                <Text style={styles.pageMarker}>Page {page.page_number}</Text>
                {page.ocr?.data?.trim() ? (
                  <Text style={styles.textContent}>{page.ocr.data}</Text>
                ) : (
                  <Text style={styles.noContent}>No OCR text available</Text>
                )}
              </View>
            ))}
          </View>

          {/* Right Column - Translation */}
          <View style={styles.column}>
            <Text style={styles.columnHeader}>{targetLanguage} (Translation)</Text>
            {pagesWithContent.map((page) => (
              <View key={`trans-${page.id}`} wrap={false}>
                <Text style={styles.pageMarker}>Page {page.page_number}</Text>
                {page.translation?.data?.trim() ? (
                  <Text style={styles.textContent}>{page.translation.data}</Text>
                ) : (
                  <Text style={styles.noContent}>No translation available</Text>
                )}
              </View>
            ))}
          </View>
        </View>

        {/* Fixed Footer */}
        <View style={styles.pageFooter} fixed>
          <Text>Source Library - Preserving rare esoteric texts</Text>
          <Text>sourcelibrary.vercel.app/book/{bookDetails.id}</Text>
        </View>
      </Page>
    </Document>
  );
};

export default BilingualPdfDocument;
